=== maartenl/Land-of-Karchan/docs/config.dtd
<?xml version="1.0"?>
<!ELEMENT root (HTMLaction, USERHeader, DATABASEHeader, CopyrightHeader,
DatabaseName, DatabaseLogin, DatabasePassword, DatabaseHost, DatabasePort,
ServerName, CGIName, MudOffLineFile, StdHelpFile, AuditTrailFile, BigFile,
ErrorFile, MudCgi, EnterCgi, NewcharCgi, LogonframeCgi, LeftframeCgi,
MMHOST, MMPORT)>
<!ELEMENT HTMLHeader (#CDATA)>
<!ELEMENT USERHeader (#CDATA)>
<!ELEMENT DATABASEHeader (#CDATA)>
<!ELEMENT CopyrightHeader (#CDATA)>
<!ELEMENT DatabaseName (#CDATA)>
<!ELEMENT DatabaseLogin (#CDATA)>
<!ELEMENT DatabasePassword (#CDATA)>
<!ELEMENT DatabaseHost (#CDATA)>
<!ELEMENT DatabasePort (#CDATA)>
<!ELEMENT ServerName (#CDATA)>
<!ELEMENT CGIName (#CDATA)>
<!ELEMENT MudOffLineFile (#CDATA)>
<!ELEMENT StdHelpFile (#CDATA)>
<!ELEMENT AuditTrailFile (#CDATA)>
<!ELEMENT BigFile (#CDATA)>
<!ELEMENT ErrorFile (#CDATA)>
<!ELEMENT MudCgi (#CDATA)>
<!ELEMENT EnterCgi (#CDATA)>
<!ELEMENT NewcharCgi (#CDATA)>
<!ELEMENT LogonframeCgi (#CDATA)>
<!ELEMENT LeftframeCgi (#CDATA)>
<!ELEMENT MMHOST (#CDATA)>
<!ELEMENT MMPORT (#CDATA)>

=== maartenl/Land-of-Karchan/server/config.xml
<?xml version="1.0"?>
<!DOCTYPE spec SYSTEM "config.dtd"><root><HTMLHeader>/karchan/mud/data/</HTMLHeader><USERHeader>/karchan/mud/tmp/</USERHeader><DATABASEHeader>/karchan/mud/data/</DATABASEHeader><CopyrightHeader>&copy; Copyright Maarten van Leunen</CopyrightHeader><DatabaseName>mud</DatabaseName><DatabaseLogin>mud</DatabaseLogin><DatabasePassword>42rakah</DatabasePassword><DatabaseHost>localhost</DatabaseHost><DatabasePort>3306</DatabasePort><ServerName>www.karchan.org</ServerName><CGIName>/cgi-bin/</CGIName><MudOffLineFile>offline.txt</MudOffLineFile><StdHelpFile>help.txt</StdHelpFile><AuditTrailFile>audit.trail</AuditTrailFile><BigFile>bigfile</BigFile><ErrorFile>error.txt</ErrorFile><MudCgi>/cgi-bin/mud.cgi</MudCgi><EnterCgi>/cgi-bin/enter.cgi</EnterCgi><NewcharCgi>/cgi-bin/newchar.cgi</NewcharCgi><LogonframeCgi>/cgi-bin/logonframe.cgi</LogonframeCgi><LeftframeCgi>/cgi-bin/leftframe.cgi</LeftframeCgi><MMHOST>karchan.org</MMHOST><MMPORT>3339</MMPORT></root>
